### ISSUE TITLE
URI encode labels and every injected value

### ISSUE THREAD

**Issue by jacomyal** [graphology/graphology-svg#1]
Right now, the very single GEXF inside the repository (for `npm run ftest`) gives an invalid SVG, because of some remaining `&` character.

**Comment by Yomguithereal** [comment]
Shouldnt you use xml entities instead?

**Comment by jacomyal** [comment]
@Yomguithereal What good would that bring / how much effort would it need?

**Comment by Yomguithereal** [comment]
What good: respecting the xml syntax. Effort: either use an entities library or a xml writer (costly) or just have a low cost xml value escaper like replacing only problematic chars as listed in this SO answer.

**Comment by Yomguithereal** [comment]
https://stackoverflow.com/questions/5709232/how-do-i-include-etc-in-xml-attribute-values

**Comment by Yomguithereal** [comment]
https://github.com/miketheprogrammer/xml-escape/blob/master/index.js

**Comment by jacomyal** [comment]
Yup, that's more a dict like this I had in mind. At least for the time being.
